### ISSUE TITLE
Deploying outside of `kube-system`

### ISSUE THREAD

**Issue by imclem** [ehashman/srecon-2019#1]
Hello,

First of all thanks for sharing this, I was not lucky enough to be at SRECON and see this talk but I've read your slides and I'm interested in deployling prometheus to my kubernetes clusters.

If I don't use the `kube-system` namespace will everything work as expected ?
Is it a good practice to deploy this kind of thing in the `kube-system` namespace ?

Thanks in advance

**Comment by ehashman** [comment]
It should not be a problem to deploy this in another namespace, although you will need to take care to ensure everything is deployed in that namespace. Because the service account for Prometheus is a ClusterRoleAccount rather than just a RoleAccount it isn't tied to a namespace.

I think it is pretty standard to deploy monitoring components in the kube-system namespace but it is certainly not required.

**Comment by imclem** [comment]
Thanks a lot !
